config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :departments do
    resources :students
    resources :courses
  end

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/student.rb
class Student < ApplicationRecord
  
  belongs_to :department
  belongs_to :course

  has_many :course_takings, foreign_key: :student_id, class_name: "Take"
  has_many :course_taking, through: :course_takings, source: :course
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # before_action :set_student, only: %i[ show edit update destroy ]
  before_action :get_department
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = @department.students
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = @department.students.build
  end

  # GET /students/1/edit
  def edit
    @student
  end

  # POST /students or /students.json
  def create
    @student = @department.students.build(student_params)
    # @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to department_students_url(@department), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to department_students_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to department_students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_department
      @department = Department.find(params[:department_id])
    end

    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :father_name, :last_name, :department_id, :course_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: [@department, student], class: "contents") do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :father_name %>
    <%= form.text_field :father_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <!--<div class="my-5">
    <%= form.label :department_id %>
    <%= form.text_field :department_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>-->
  <%# <div class="my-5"> %>
  <%# <%= form.label :course_id %>
  <%# <%= form.text_field :course_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <%# <%= collection_select(:student, :department_id, @department.courses, :id, :course_name, prompt: true) %>
  <%# </div> %>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-1 px-4 bg-green-300 inline-block font-medium mt-5 cursor-pointer" %>
  </div>
<% end %>

app/views/students/_student.html.erb
<tbody id="<%= dom_id student %>" class="overflow-x-auto relative shadow-md sm:rounded-lg">
  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <%= student.first_name %>
    </th>
    <td class="py-4 px-6">
      <%= student.father_name %>
    </td>
    <td class="py-4 px-6">
      <%= student.last_name %>
    </td>
    <td class="py-4 px-6">
      <%= student.department.department_name %>
    </td>
    <td class="py-4 px-6 text-center">
      <%= link_to "Edit", edit_department_student_path(@department, student), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>
    </td>
  </tr>
</tbody>

app/views/students/_students_layout.html.erb
<div class="m-0 font-sans antialiased font-normal text-size-base leading-default bg-gray-50 text-slate-500">
  <div class="ease-soft-in-out xl:ml-68.5 relative h-full max-h-screen rounded-xl transition-all duration-200">
    <%= render "shared/navbar_dashboard" %>
    <%= render "shared/aside_dashboard" %>
    <%= yield %>
  </div>
</div>

app/views/students/edit.html.erb
<%= render layout: "students_layout" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing student</h1>
    <%= render "form", student: @student %>
    <%# <%= link_to "Show this student", @student, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to students", department_students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/students/index.html.erb
<%= render layout: "students_layout" do %>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div class="flex justify-between items-center mr-5 pr-4">
      <h1 class="font-bold text-4xl">Students</h1>
      <%= link_to "Add Students", new_department_student_url, class: "rounded-lg py-1 px-4 bg-green-300 inline-block font-medium mt-5" %>
    </div>
    <div id="students" class="min-w-full">
      <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="py-3 px-6">
              First Name
            </th>
            <th scope="col" class="py-3 px-6">
              Father Name
            </th>
            <th scope="col" class="py-3 px-6">
              Last Name
            </th>
            <th scope="col" class="py-3 px-6">
              Department
            </th>
            <th scope="col" class="py-3 px-6">
            </th>
          </tr>
        </thead>
        <%= render @students %>
      </table>
    </div>
  </div>
<% end %>

app/views/students/new.html.erb
<%= render layout: "students_layout" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New student</h1>
    <%= render "form", student: @student %>
    <%= link_to 'Back to students', department_students_url, class: "rounded-lg py-1 px-4 bg-gray-100 inline-block font-medium mt-5 cursor-pointer" %>
  </div>
<% end %>

app/views/students/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @student %>

    <%= link_to 'Edit this student', edit_student_path(@student), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this student', student_path(@student), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to students', students_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>