config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :departments do
    resources :students
    resources :courses
  end

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <div id="toast-default" class="<%= flash_classes(type) %>">
    <%= message %>
    <button class="ml-auto hover:cursor-pointer z-999" data-dismiss-target="#toast-default" aria-label="Close">
      <svg xmlns="http://www.w3.org/2000/svg" class="fill-current text-white-700" viewBox="0 0 16 16" width="20" height="20"><path fill-rule="evenodd" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path></svg>
    </button>
  </div>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Kickoff Tailwind" %>
  </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'custom', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", defer: true %>
  <%= javascript_importmap_tags %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Popper -->
  <script src="https://unpkg.com/@popperjs/core@2"></script>
</head>

app/views/shared/_navbar.html.erb
<% if !user_signed_in? %>
  <nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto lg:px-0 px-4 <%= nav_classes %>" data-controller="nav">
    <div class="flex items-center mr-6 flex-no-shrink">
      <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
        <span class="sr-only">Productivity Improvement and Excellency Center</span>
        <%# Remove this logo and add your own %>
        <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
      <% end %>
    </div>
    <div class="block lg:hidden">
      <%# Mobile nav toggle %>
      <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
        <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
      </button>
    </div>
    <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
      <div class="lg:flex-grow">
        <%= link_to "Basic Link", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
      </div>
      <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
        <div><%# More links can go here %></div>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>
        <span class="h-5 w-px bg-gray-200 mx-3"></span>
        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_navbar_dashboard.html.erb
<!-- Navbar -->
<nav class="relative flex flex-wrap items-center justify-between px-0 py-2 mx-6 transition-all shadow-none duration-250 ease-soft-in rounded-2xl lg:flex-nowrap lg:justify-start" navbar-main navbar-scroll="true">
  <div class="flex items-center justify-between w-full px-4 py-1 mx-auto flex-wrap-inherit">
    <nav>
      <!-- breadcrumb -->
      <%# <h6 class="mb-0 font-bold capitalize">Dashboard</h6> %>
    </nav>
    <div class="flex items-center mt-2 grow sm:mt-0 sm:mr-6 md:mr-0 lg:flex lg:basis-auto">
      <ul class="flex flex-row justify-start pl-0 mb-0 list-none md:w-full md-max:w-full md:pr-4">
        <!-- online builder btn  -->
        <li class="flex items-center mr-2">
          <% if @department && @department.id %>
            <strong class="bg-gradient-red px-3.6-em text-size-xs-em rounded-1.8 py-2.2-em inline-block whitespace-nowrap text-center align-baseline font-bold uppercase leading-none text-white"><%= @department.department_name  %></strong>
          <% end %>
        </li>
        <li class="flex items-center mr-3">
          <% if @department && @department.id %>
            <%= link_to 'Students', department_students_path(@department) , class: "inline-block text-sm px-4 py-2 leading-none border rounded text-bluePostsCreationPolicy border-black hover:border-transparent hover:text-teal-500 hover:bg-gray mt-4 lg:mt-0"%>
          <% end %>
        </li>
        <li class="flex items-center mr-3">
          <% if @department && @department.id %>
            <%= link_to 'Courses', department_courses_path(@department) , class: "inline-block text-sm px-4 py-2 leading-none border rounded text-blue border-black hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0"%>
          <% end %>
        </li>
        <li class="flex items-center">
          <% if @department  %>
            <%= link_to 'Back to Department', departments_path , class: "inline-block text-sm px-4 py-2 leading-none border rounded text-blue border-black hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0"%>
          <% end %>
        </li>
        <li class="flex items-center ml-auto">
          <a class="inline-block px-8 py-2 mb-0 mr-4 font-bold text-center uppercase align-middle transition-all bg-transparent border border-solid rounded-lg shadow-none cursor-pointer leading-pro border-green-500 ease-soft-in text-size-xs hover:scale-102 active:shadow-soft-xs text-gray-500 hover:border-green-500 active:bg-green-500 active:hover:text-gray-500 hover:text-gray-500 tracking-tight-soft hover:bg-transparent hover:opacity-75 hover:shadow-none active:text-white active:hover:bg-transparent" href="users/edit"> <%= current_user.first_name %> <%= current_user.father_name %> </a>
        </li>
        <li class="flex items-center">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"
            block px-0 py-2 font-semibold transition-all ease-nav-brand text-size-sm text-slate-500" %>
        </a>
      </li>
      <li class="flex items-center pl-4 xl:hidden">
        <a href="javascript:;" class="block p-0 transition-all ease-nav-brand text-size-sm text-slate-500" sidenav-trigger>
          <div class="w-4.5 overflow-hidden">
            <i class="ease-soft mb-0.75 relative block h-0.5 rounded-sm bg-slate-500 transition-all"></i>
            <i class="ease-soft mb-0.75 relative block h-0.5 rounded-sm bg-slate-500 transition-all"></i>
            <i class="ease-soft relative block h-0.5 rounded-sm bg-slate-500 transition-all"></i>
          </div>
        </a>
      </li>
    </ul>
  </div>
</div>
</nav>
<!-- end Navbar -->