config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :departments do
    resources :students
    resources :courses
  end

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :students
    has_many :courses
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user! and :is_admin?
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:department_name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p class="my-5">
    <% if action_name != "show" %>
      <%= link_to "#{department.department_name if current_page?(controller: 'departments', action: 'index') }", department_students_path(department), class: "rounded-lg py-2 px-5 bg-blue-300 inline-block font-medium hover:text-blue-600 hover:bg-blue-100 hover:border-green-300" %>
    <% end %>
  </p>
  <hr class="mt-6">
</div>

app/views/departments/_departments_layout.html.erb
<div class="m-0 font-sans antialiased font-normal text-size-base leading-default bg-gray-50 text-slate-500">
  <div class="ease-soft-in-out xl:ml-68.5 relative h-full max-h-screen rounded-xl transition-all duration-200">
    <%= render "shared/navbar_dashboard" %>
    <%= render "shared/aside_dashboard" %>
    <%= yield %>
  </div>
</div>

app/views/departments/_form.html.erb
<%= form_with(model: department, class: "contents") do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :department_name %>
    <%= form.text_field :department_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing department</h1>

  <%= render "form", department: @department %>

  <%= link_to "Show this department", @department, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to departments", departments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/departments/index.html.erb
<%= render layout: "departments_layout" do %>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div class="flex justify-between items-center mr-5 pr-4">
      <h1 class="font-bold text-4xl">Departments</h1>
      <%= link_to 'New department', new_department_path, class: "rounded-lg py-1 px-4 bg-green-300 inline-block font-medium mt-5" %>
    </div>
    <div id="departments" class="min-w-full">
      <%= render @departments %>
    </div>
  </div>
<% end %>

app/views/departments/new.html.erb
<%= render layout: "departments_layout" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New department</h1>
    <%= render "form", department: @department %>
    <%= link_to 'Back to departments', departments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/departments/show.html.erb
<%= render layout: "departments_layout" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <div class="mx-auto">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      <%= render @department %>
    </div>
  </div>
<% end %>